# Generated by Django 4.1.2 on 2022-11-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keeper',
            options={'verbose_name': 'Keeper'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Owner'},
        ),
    ]
