# Generated by Django 4.1.2 on 2022-11-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_end_date_remove_booking_start_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.booking'),
        ),
    ]
