# Generated by Django 4.1.2 on 2022-11-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_availability_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeper',
            name='pet_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10),
        ),
    ]
