# Generated by Django 4.1.2 on 2022-11-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
