# Generated by Django 4.1.2 on 2022-11-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('pets', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keepers', to='users.keeper'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets.pet'),
        ),
    ]
