# Generated by Django 4.1.2 on 2022-11-28 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_availability_booking'),
        ('bookings', '0003_remove_booking_keeper_remove_booking_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.availability'),
        ),
    ]
